### ISSUE TITLE
Key isn't always found in vehicles. #2

### ISSUE THREAD

**Issue by nykroza** [Xseba360/esx_locksystem#3] opened 2018-08-16 17:47 UTC
It's kind a replicate of the other issues..
But once the FiveM forum I added what you did in the policejob, mecano etc
also in the server side of vehicleshop

My percentage is at 99% but if I take out a vehicle from the police garage it doesn't give me the key, I still need to press U to find it

If we buy a vehicle from the vehicleshop, we're never able to find the key even if we logout and reconnect, put the vehicle in the garage and take it out again

**Comment by XxFri3ndlyxX** [comment] 2018-08-23 17:45
Iv'e been trying to make this work so when you buy you have keys but it still have 50/50  chance of having keys. Not sure what to do here. Works perfectly with jobs tho well i only tested cops yet and works great.

**Comment by Xseba360** [comment] 2018-08-28 00:36
duplicate of #2

**Closed as completed by Xseba360** 2018-08-28 00:36 UTC
Labels: duplicate
